### PR TITLE
Use group of clusters to be able to select what to compile in create-vanilla-SCDB.sh

### PR DESCRIPTION
**Pull request by jouvin**
Intended to help with https://github.com/quattor/scdb/issues/34.

### CODE REVIEW

**Comment by Pansanel** [comment]
This PR works only if the `clusters.groups.enable` variable is set to `true` in the [quattor.build.xml](https://github.com/quattor/scdb/blob/master/quattor.build.xml) file. However, I do not see this modification in this file.

**Comment by jrha** [comment]
Unless @Pansanel's comment is addressed, this cannot be part of 15.2.

**Comment by jouvin** [comment]
@Pansanel No, the `quattor.build.xml` file should **never** been modified, it defines default values that can be customized with file `quattor.build.properties`.  And `create-vanilla-SCDB.sh` has been modified to create this file with the appropriate value based on the Quattor version (see https://github.com/quattor/scdb/issues/33).

**Comment by jrha** [comment]
@Pansanel, happy?

**Comment by jouvin** [comment]
Please, be sure to have it in the final 15.2 or we'll create another mess... Idon't see how @Pansanel could be unhappy :-)

**Comment by jouvin** [comment]
I missed there was a merge conflict, I'll look at it...

**Comment by Pansanel** [comment]
I have tested the script. It works fine. Once it can be merged, I will do it.

**Comment by jouvin** [comment]
@Pansanel should be fixed (conflict due to the fact we update `cluster.build.properties` during the release process but this file is relocated by this PR).

Don't forget to merge https://github.com/quattor/scdb/issues/33 too.

**Comment by Pansanel** [comment]
I cannot merge https://github.com/quattor/scdb/pull/33, I don't have write access.

**Comment by jouvin** [comment]
Should be fixed.

**Pull request merged**
